SET DEFINE OFF

CREATE TABLE rae.customer (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  customer_name VARCHAR2(100 BYTE) NOT NULL,
  email VARCHAR2(100 BYTE) NOT NULL,
  phone_number VARCHAR2(15 BYTE),
  address VARCHAR2(4000 BYTE),
  PRIMARY KEY (customer_id),
  UNIQUE (email)
);

