SET DEFINE OFF

DECLARE
  objExists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO objExists FROM ALL_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OWNER = 'RAE' AND OBJECT_NAME = 'CATEGORY';
  IF (objExists > 0) THEN
    EXECUTE IMMEDIATE 'DROP TABLE rae."CATEGORY"';
  END IF;
END;
/

