SET DEFINE OFF

DECLARE
  objExists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO objExists FROM ALL_OBJECTS WHERE OBJECT_TYPE = 'SYNONYM' AND OWNER = 'RAE' AND OBJECT_NAME = 'FLYWAY_SNAPSHOT_HISTORY';
  IF (objExists > 0) THEN
    EXECUTE IMMEDIATE 'DROP SYNONYM rae.flyway_snapshot_history';
  END IF;
END;
/

