CREATE TABLE rae."USERS" (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR2(50 BYTE) NOT NULL,
  password_hash VARCHAR2(255 BYTE) NOT NULL,
  role_id NUMBER NOT NULL,
  category_id NUMBER,
  PRIMARY KEY (user_id),
  UNIQUE (username),
  CONSTRAINT fk_users_category FOREIGN KEY (category_id) REFERENCES rae."CATEGORY" (category_id)
);